-- Criação da tabela PERFIL
CREATE TABLE PERFIL (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela USUARIO
CREATE TABLE USUARIO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PERFIL_ID INT NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
    FOREIGN KEY (PERFIL_ID) REFERENCES PERFIL(ID),
)

-- Criação da tabela PERGUNTA
CREATE TABLE PERGUNTA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PERGUNTA VARCHAR(255) NOT NULL,
    INICIO_VIGENCIA DATETIME NOT NULL,
    FIM_VIGENCIA DATETIME NOT NULL,
    USUARIO_ID INT NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
)

-- Criação da tabela RESPOSTA
CREATE TABLE RESPOSTA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    TIPO INT NOT NULL,
    INICIO_VIGENCIA DATETIME NOT NULL,
    FIM_VIGENCIA DATETIME NOT NULL,
    USUARIO_ID INT NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
)

-- Criação da tabela SISTEMA
CREATE TABLE SISTEMA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela PROCESSO
CREATE TABLE PROCESSO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela PARAMETRO
CREATE TABLE PARAMETRO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela STATUS_DISPARO
CREATE TABLE STATUS_DISPARO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela TIPO_PESQUISA
CREATE TABLE TIPO_PESQUISA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela PUBLICO_ALVO
CREATE TABLE PUBLICO_ALVO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela DESTINATARIO
CREATE TABLE DESTINATARIO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CELULAR VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME
)

-- Criação da tabela PESQUISA
CREATE TABLE PESQUISA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    SLUG VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    REENVIO BIT NOT NULL,
    QUANTIDADE_REENVIO INT,
    PERIODICIDADE_REENVIO INT,
    COMENTARIO_RANGE_NOTA BIT NOT NULL,
    RANGE_INICIAL INT,
    RANGE_FINAL INT,
    EMAIL_TI VARCHAR(255) NOT NULL,
    EMAIL_NEGOCIO VARCHAR(255) NOT NULL,
    INICIO_VIGENCIA DATETIME NOT NULL,
    FIM_VIGENCIA DATETIME NOT NULL,
    TIPO_PESQUISA_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    SISTEMA_ID INT NOT NULL,
    PROCESSO_ID INT NOT NULL,
    PARAMETRO_ID INT NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME,
    FOREIGN KEY (TIPO_PESQUISA_ID) REFERENCES TIPO_PESQUISA(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (SISTEMA_ID) REFERENCES SISTEMA(ID),
    FOREIGN KEY (PROCESSO_ID) REFERENCES PROCESSO(ID),
    FOREIGN KEY (PARAMETRO_ID) REFERENCES PARAMETRO(ID),
);

-- Criação da tabela PESQUISA_SMS
CREATE TABLE PESQUISA_SMS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CONDICAO_DISPARO VARCHAR(255) NOT NULL,
    MENSAGEM_SMS VARCHAR(255) NOT NULL,
    TIPO_RESPOSTA_SMS VARCHAR(255) NOT NULL,
    PESQUISA_ID INT NOT NULL,
    FOREIGN KEY (PESQUISA_ID) REFERENCES TIPO_PESQUISA(ID)
);

-- Criação da tabela PESQUISA_EMAIL
CREATE TABLE PESQUISA_EMAIL (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CONDICAO_DISPARO VARCHAR(255) NOT NULL,
    MENSAGEM_EMAIL VARCHAR(255) NOT NULL,
    MENSAGEM_HTML VARCHAR(255) NOT NULL,
    PESQUISA_ID INT NOT NULL,
    FOREIGN KEY (PESQUISA_ID) REFERENCES TIPO_PESQUISA(ID)
);

-- Criação da tabela DISPARO
CREATE TABLE DISPARO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    COD_AGENDAMENTO INT NOT NULL,
    PESQUISA_ID INT NOT NULL,
    STATUS_DISPARO_ID INT NOT NULL,
    DESTINATARIO_ID INT NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME,
    FOREIGN KEY (PESQUISA_ID) REFERENCES PESQUISA(ID),
    FOREIGN KEY (STATUS_DISPARO_ID) REFERENCES STATUS_DISPARO(ID),
    FOREIGN KEY (DESTINATARIO_ID) REFERENCES DESTINATARIO(ID)
)

-- Criação da tabela PESQUISA_PERGUNTA_RESPOSTA
CREATE TABLE PESQUISA_PERGUNTA_RESPOSTA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PESQUISA_ID INT NOT NULL,
    PERGUNTA_ID INT NOT NULL,
    RESPOSTA_ID INT NOT NULL,
    FOREIGN KEY (PESQUISA_ID) REFERENCES PESQUISA(ID),
    FOREIGN KEY (PERGUNTA_ID) REFERENCES PERGUNTA(ID),
    FOREIGN KEY (RESPOSTA_ID) REFERENCES RESPOSTA(ID)
)

-- Criação da tabela RESPOSTA_PESQUISA_PERGUNTA_RESPOSTA
CREATE TABLE RESPOSTA_PESQUISA_PERGUNTA_RESPOSTA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    RESPOSTA INT NOT NULL,
    PESQUISA_PERGUNTA_RESPOSTA_ID INT NOT NULL,
    COMENTARIO VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME,
    FOREIGN KEY (PESQUISA_PERGUNTA_RESPOSTA_ID) REFERENCES PESQUISA_PERGUNTA_RESPOSTA(ID),
)

-- Criação da tabela PESQUISA_PUBLICO_ALVO
CREATE TABLE PESQUISA_PUBLICO_ALVO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PESQUISA_ID INT NOT NULL,
    PUBLICO_ALVO_ID INT NOT NULL,
    FOREIGN KEY (PESQUISA_ID) REFERENCES PESQUISA(ID),
    FOREIGN KEY (PUBLICO_ALVO_ID) REFERENCES PUBLICO_ALVO(ID),
)

-- Criação da tabela AVALIACAO_DE_JORNADA
CREATE TABLE AVALIACAO_DE_JORNADA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    TIPO INT NOT NULL,
    TEXTO_ADICIONAL VARCHAR(255) NOT NULL,
    INICIO_VIGENCIA DATETIME NOT NULL,
    FIM_VIGENCIA DATETIME NOT NULL,
    USUARIO_ID INT NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
)

-- Criação da tabela PESQUISA_PERGUNTA_AVALIACAO_DE_JORNADA
CREATE TABLE PESQUISA_PERGUNTA_AVALIACAO_DE_JORNADA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PESQUISA_ID INT NOT NULL,
    PERGUNTA_ID INT NOT NULL,
    AVALIACAO_DE_JORNADA_ID INT NOT NULL,
    FOREIGN KEY (PESQUISA_ID) REFERENCES PESQUISA(ID),
    FOREIGN KEY (PERGUNTA_ID) REFERENCES PERGUNTA(ID),
    FOREIGN KEY (AVALIACAO_DE_JORNADA_ID) REFERENCES AVALIACAO_DE_JORNADA(ID)
)

-- Criação da tabela RESPOSTA_PESQUISA
CREATE TABLE RESPOSTA_PESQUISA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PESQUISA_PERGUNTA_AVALIACAO_DE_JORNADA_ID INT NOT NULL,
    RESPOSTA BIT NOT NULL,
    CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
    ATUALIZADO_EM DATETIME,
    DELETADO_EM DATETIME,
    FOREIGN KEY (PESQUISA_PERGUNTA_AVALIACAO_DE_JORNADA_ID) REFERENCES PESQUISA_PERGUNTA_AVALIACAO_DE_JORNADA(ID),
)